
name: forecast-binder
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy=1.25.2
  - scipy=1.10.1
  - scikit-learn=1.3.2
  - pmdarima=2.0.4
  - prophet=1.1
  - lightgbm=4.0
  - matplotlib
  - pandas
